path: /afs/cern.ch/work/a/aguzel/private/bamboo_105/HHtoWWbb_Run3/output/singleTRG-2022/

outputDir: /afs/cern.ch/work/a/aguzel/private/wwbb-run3-datacards/output/singleTRG-2022/

use_syst: True

yamlName: plots.yml

era:
  - "2022"
  - "2022EE"


plotIt:
  configuration:
    width: 800
    height: 800
    margin-left: 0.125
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.1
    luminosity-label: '%1$.2f fb^{-1} (13.6 TeV)'
    experiment: " "
    extra-label: Private work (CMS simulation)
    luminosity-error: 0.014 # https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3
    show-overflow: true
    error-fill-style: 3154
    error-fill-color: "#ee556270"
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: "#aa556270"
    ratio-fit-line-color: "#0B486B"
    y-axis-format: "%1% / %2$.2f"
    blinded-range-fill-style: 1001
    blinded-range-fill-color: "#29556270"
    yields-table-align: v
    yields-table-text-align: l
    book-keeping-file: plots.root
  legend:
    position: [0.4, 0.65, 0.9, 0.9]
  plotdefaults:
    # y-axis-range: [0.00001, 50000000]
    normalized: False
    y-axis: "Events"
    log-y: both
    y-axis-show-zero: True
    save-extensions: [png]
    show-ratio: True
    sort-by-yields: True
    legend-columns: 4
    ratio-y-axis: "Data / MC"
    ratio-y-axis-range: [0.8, 1.2]

# combineConfigs:

normSyst:
  lumi:
    val: 1.013
    group: 
      - TT
      - DY
      - others

shapeSyst:
  # To discard unwanted systematics
  # some_unwanted_syst: discard
  btagSF_shape_cferr1: btagSF_shape_cferr1
  btagSF_shape_lfstats1_2022: btagSF_shape_lfstats1_2022
  btagSF_shape_lfstats1_2022EE: btagSF_shape_lfstats1_2022EE
  pileup: pileup
  btagSF_shape_hfstats2_2022: btagSF_shape_hfstats2_2022
  btagSF_shape_hfstats2_2022EE: btagSF_shape_hfstats2_2022EE
  btagSF_shape_lfstats2_2022: btagSF_shape_lfstats2_2022
  btagSF_shape_lfstats2_2022EE: btagSF_shape_lfstats2_2022EE
  btagSF_shape_cferr2: btagSF_shape_cferr2
  jesTotal: jesTotal
  btagSF_shape_hfstats1_2022: btagSF_shape_hfstats1_2022
  btagSF_shape_hfstats1_2022EE: btagSF_shape_hfstats1_2022EE
  btagSF_shape_hf: btagSF_shape_hf
  btagSF_shape_lf: btagSF_shape_lf
  jer0: jer0
  jer1: jer1
  jer2: jer2
  jer3: jer3
  jer4: jer4
  jer5: jer5
  elIdSF: elIdSF
  elTrgSF: elTrgSF
  muonIdSF: muonIdSF
  muonIsoSF: muonIsoSF
  muonTrgSF: muonTrgSF
  pileup: pileup
  ZpT1: ZpT1
  ZpT2: ZpT2
  ZpT3: ZpT3
  ZpT4: ZpT4
  ZpT5: ZpT5
  ZpT6: ZpT6
  ZpT7: ZpT7
  ZpT8: ZpT8
  ZpT9: ZpT9
  ZpT10: ZpT10

# quantiles :   
#   - &quant5 [0., 0.6, 0.7, 0.8, 0.9 ,1.]
#   - &quant3 [0., 0.33, 0.66, 1.]
# backgrounds: &bkg [TT, DY, others]
# signal: &signal [ggHH_kl_1_kt_1_hbbhww, ggHH_kl_2p45_kt_1_hbbhww, ggHH_kl_5_kt_1_hbbhww]

# rebin:
#   # Apply quantile binning to all ML score distributions
#   # keys should match the histConverter keys
# rebin:
#   DL_boosted:
#     method: classic
#     params:
#       # Merge every 2 bins of the original histogram into one.
#       - 2
#   DL_resolved1b:
#     method: classic
#     params:
#       - 2
#   DL_resolved2b:
#     method: classic
#     params:
#       - 2
#   DL_VBF_boosted:
#     method: classic
#     params:
#       - 2
#   DL_VBF_resolved:
#     method: classic
#     params:
#       - 2


histConverter:
  DL_boosted:
    - DL_boosted_ml_score
  DL_resolved1b:
    - DL_resolved1b_ml_score
  DL_resolved2b:
    - DL_resolved2b_ml_score
  DL_VBF_boosted:
    - DL_VBF_boosted_ml_score
  DL_VBF_resolved:
    - DL_VBF_resolved_ml_score

groups:
  "2022": !include samples_2022.yml
  "2022EE": !include samples_2022EE.yml