path: /afs/cern.ch/work/a/aguzel/private/bamboo_105/HHtoWWbb_Run3/output/v1.4.6-2023-mva

outputDir: /afs/cern.ch/work/a/aguzel/private/wwbb-run3-datacards/output/v1.4.6-2023-mva

use_syst: True

yamlName: plots.yml

era:
  - "2023"
  - "2023BPix"

plotIt:
  configuration:
    width: 800
    height: 800
    margin-left: 0.125
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.1
    luminosity-label: '%1$.2f fb^{-1} (13.6 TeV)'
    experiment: " "
    extra-label: Private work (CMS simulation)
    luminosity-error: 0.013 # https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3
    show-overflow: true
    error-fill-style: 3154
    error-fill-color: "#ee556270"
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: "#aa556270"
    ratio-fit-line-color: "#0B486B"
    y-axis-format: "%1% / %2$.2f"
    blinded-range-fill-style: 1001
    blinded-range-fill-color: "#29556270"
    yields-table-align: v
    yields-table-text-align: l
    book-keeping-file: plots.root
  legend:
    position: [0.4, 0.6, 0.9, 0.9]
  plotdefaults:
    # y-axis-range: [0.00001, 50000000]
    normalized: False
    y-axis: "Events"
    log-y: both
    y-axis-show-zero: True
    save-extensions: [png]
    show-ratio: True
    sort-by-yields: True
    legend-columns: 4
    ratio-y-axis: "Data / MC"
    ratio-y-axis-range: [0.8, 1.2]

# combineConfigs:

normSyst:
  lumi:
    val: 1.013
    group: 
      - TT
      - DY
      - ST
      - VV
      - VJets
      - other
  footer:
    - "TTbar_norm rateParam * TTbar 1 [0,5]"
    - "DY_norm rateParam * DY 1 [0,5]"

shapeSyst:
  # # Discard unwanted systematics
  # some_unwanted_syst: discard
  btagSF_shape_cferr1: btagSF_shape_cferr1
  btagSF_shape_lfstats1_2023: btagSF_shape_lfstats1_2023
  btagSF_shape_lfstats1_2023BPix: btagSF_shape_lfstats1_2023BPix
  pileup: pileup
  btagSF_shape_hfstats2_2023: btagSF_shape_hfstats2_2023
  btagSF_shape_hfstats2_2023BPix: btagSF_shape_hfstats2_2023BPix
  btagSF_shape_lfstats2_2023: btagSF_shape_lfstats2_2023
  btagSF_shape_lfstats2_2023BPix: btagSF_shape_lfstats2_2023BPix
  btagSF_shape_cferr2: btagSF_shape_cferr2
  jesTotal: jesTotal
  btagSF_shape_hfstats1_2023: btagSF_shape_hfstats1_2023
  btagSF_shape_hfstats1_2023BPix: btagSF_shape_hfstats1_2023BPix
  btagSF_shape_hf: btagSF_shape_hf
  btagSF_shape_lf: btagSF_shape_lf
  jer0: jer0
  jer1: jer1
  jer2: jer2
  jer3: jer3
  jer4: jer4
  jer5: jer5
  topPtRW: topPtRW
  elIdSF: elIdSF
  elTrgSF: elTrgSF
  muonIdSF: muonIdSF
  muonIsoSF: muonIsoSF
  muonTrgSF: muonTrgSF
  ZpT: ZpT
  dileptonTRGSF: dileptonTRGSF

quantiles: &quant [0., 0.4, 0.45, 0.5, 0.55, 0.625, 0.75, 0.875, 1.]
backgrounds: &back [TT, DY, VV, VJets]

# rebin:
#   DL_score:
#     method: quantile
#     params: [*quant, *back]

#histCorrections:

histConverter:
  DL_boosted:
    - DL_boosted_ml_score
  DL_resolved1b:
    - DL_resolved1b_ml_score
  DL_resolved2b:
    - DL_resolved2b_ml_score
  DL_VBF_boosted:
    - DL_VBF_boosted_ml_score
  DL_VBF_resolved:
    - DL_VBF_resolved_ml_score

groups:
  "2023": !include samples_2023.yml
  "2023BPix": !include samples_2023BPix.yml