path:
  "2022":
   - /afs/cern.ch/work/a/aguzel/private/bamboo_105/HHtoWWbb_Run3/output/SR_2022
  "2022EE":
    - /afs/cern.ch/work/a/aguzel/private/bamboo_105/HHtoWWbb_Run3/output/SR_2022EE
  "2023":
   - /afs/cern.ch/work/a/aguzel/private/bamboo_105/HHtoWWbb_Run3/output/SR_2023
  "2023BPix":
    - /afs/cern.ch/work/a/aguzel/private/bamboo_105/HHtoWWbb_Run3/output/SR_2023BPix

outputDir: /afs/cern.ch/work/a/aguzel/private/wwbb-run3-datacards/output/v1.4.7

use_syst: True

# textfiles:

yamlName: plots.yml

era:
  - "2022"
  - "2022EE"
  - "2023"
  - "2023BPix"

plotIt:
  # unitary_bin_width: true
  # plotdefaults:
    # y-axis: "Events / Unit Score"
  configuration:
    width: 800
    height: 800
    margin-left: 0.125
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.1
    luminosity-label: '%1$.2f fb^{-1} (13.6 TeV)'
    experiment: "CMS"
    extra-label: Work in Progress
    luminosity-error: 0.0135 # https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3
    show-overflow: true
    error-fill-style: 3154
    error-fill-color: "#ee556270"
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: "#aa556270"
    ratio-fit-line-color: "#0B486B"
    y-axis-format: "%1% / %2$.2f"
    blinded-range-fill-style: 1001
    blinded-range-fill-color: "#29556270"
    yields-table-align: v
    yields-table-text-align: l
    book-keeping-file: plots.root
  legend:
    position: [0.4, 0.55, 0.9, 0.9]
  plotdefaults:
    y-axis-range: [0.00001, 100000000]
    normalized: False
    y-axis: "Events"
    log-y: both
    y-axis-show-zero: True
    save-extensions: [png]
    show-ratio: True
    sort-by-yields: True
    legend-columns: 4
    ratio-y-axis: "Data / MC"
    ratio-y-axis-range: [0.8, 1.2]
  legend:
    position:
      - 0.2
      - 0.7
      - 0.9
      - 0.9
    columns: 3

# combineConfigs:

normSyst:
  lumi:
    val: 1.0135
    group: 
      - TT
      - DY
      - ST
      - VV
      - VJets
      - other
  footer:
    - "TTbar_norm rateParam * TTbar 1 [0,5]"
    - "DY_norm rateParam * DY 1 [0,5]"

shapeSyst:
  btagSF_shape_cferr1: btagSF_shape_cferr1
  btagSF_shape_lfstats1_2022: btagSF_shape_lfstats1_2022
  btagSF_shape_lfstats1_2022EE: btagSF_shape_lfstats1_2022EE
  btagSF_shape_lfstats1_2023: btagSF_shape_lfstats1_2023
  btagSF_shape_lfstats1_2023BPix: btagSF_shape_lfstats1_2023BPix
  btagSF_shape_hfstats2_2022: btagSF_shape_hfstats2_2022
  btagSF_shape_hfstats2_2022EE: btagSF_shape_hfstats2_2022EE
  btagSF_shape_hfstats2_2023: btagSF_shape_hfstats2_2023
  btagSF_shape_hfstats2_2023BPix: btagSF_shape_hfstats2_2023BPix
  btagSF_shape_lfstats2_2022: btagSF_shape_lfstats2_2022
  btagSF_shape_lfstats2_2022EE: btagSF_shape_lfstats2_2022EE
  btagSF_shape_lfstats2_2023: btagSF_shape_lfstats2_2023
  btagSF_shape_lfstats2_2023BPix: btagSF_shape_lfstats2_2023BPix
  btagSF_shape_cferr2: btagSF_shape_cferr2
  jesTotal: discard
  btagSF_shape_hfstats1_2022: btagSF_shape_hfstats1_2022
  btagSF_shape_hfstats1_2022EE: btagSF_shape_hfstats1_2022EE
  btagSF_shape_hfstats1_2023: btagSF_shape_hfstats1_2023
  btagSF_shape_hfstats1_2023BPix: btagSF_shape_hfstats1_2023BPix
  btagSF_shape_hf: btagSF_shape_hf
  btagSF_shape_lf: btagSF_shape_lf
  jer0: jer0
  jer1: jer1
  jer2: jer2
  jer3: jer3
  jer4: jer4
  jer5: jer5
  topPtRW: topPtRW
  elIdSF: elIdSF
  elTrgSF: elTrgSF
  muonIdSF: muonIdSF
  muonIsoSF: muonIsoSF
  muonTrgSF: muonTrgSF
  pileup: pileup
  ZpT: ZpT
  dileptonTRGSF: dileptonTRGSF
  QCDscale_ttbar: QCDscale_ttbar
  QCDscale_V: QCDscale_V
  QCDscale_VV: QCDscale_VV
  QCDscale_ggH: QCDscale_ggH
  QCDscale_qqH: QCDscale_qqH
  QCDscale_VH: QCDscale_VH
  QCDscale_ttH: QCDscale_ttH
  PDFalphaS_gq: PDFalphaS_gq
  PDFalphaS_gg: PDFalphaS_gg
  PDFalphaS_qq: PDFalphaS_qq
  PDFalphaS_ggH: PDFalphaS_ggH
  PDFalphaS_qqH: PDFalphaS_qqH
  PDFalphaS_VH: PDFalphaS_VH
  PDFalphaS_ttH: PDFalphaS_ttH
  muRF_ttbar: muRF_ttbar
  muRF_DY: muRF_DY
  muRF_ST: muRF_ST
  muRF_VV: muRF_VV
  muRF_ttV: muRF_ttV
  muRF_singleH: muRF_singleH
  muRF_bbWW: muRF_bbWW
  muRF_bbZZ: muRF_bbZZ
  muRF_bbtautau: muRF_bbtautau
  pdfShape_ttbar: pdfShape_ttbar
  pdfShape_DY: pdfShape_DY
  pdfShape_ST: pdfShape_ST
  pdfShape_VV: pdfShape_VV
  pdfShape_ttV: pdfShape_ttV
  pdfShape_singleH: pdfShape_singleH
  pdfShape_bbWW: pdfShape_bbWW
  pdfShape_bbZZ: pdfShape_bbZZ
  pdfShape_bbtautau: pdfShape_bbtautau
  psISR: psISR
  psFSR_ttbar: psFSR_ttbar
  psFSR_DY: psFSR_DY
  psFSR_ST: psFSR_ST
  psFSR_VV: psFSR_VV
  psFSR_ttV: psFSR_ttV
  psFSR_singleH: psFSR_singleH
  ak8BBCC: ak8BBCC
  ak8BBCC_tau21: ak8BBCC_tau21
  ak8BBCC_msd: ak8BBCC_msd


thresholds_10: &thr10 [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
thresholds_8: &thr8 [1, 4, 9, 16, 25, 36, 49, 64]
thresholds_3: &thr3 [1, 4, 9]
thresholds_4: &thr4 [1, 4, 9, 16]
thresholds_1: &thr1 [1]
backgrounds: &backgrounds [TTbar, DY, ST, VV, VJets, others]

rebin:
  DL_boosted:
    method: threshold2
    params: [*thr3, *backgrounds]
  DL_resolved1b:
    method: threshold2
    params: [*thr10, *backgrounds]
  DL_resolved2b:
    method: threshold2
    params: [*thr8, *backgrounds]
  DL_VBF_boosted:
    method: threshold2
    params: [*thr1, *backgrounds]
  DL_VBF_resolved:
    method: threshold2
    params: [*thr4, *backgrounds]

#histCorrections:

histConverter:
  DL_boosted:
    - DL_boosted_ml_score
  DL_resolved1b:
    - DL_resolved1b_ml_score
  DL_resolved2b:
    - DL_resolved2b_ml_score
  DL_VBF_boosted:
    - DL_VBF_boosted_ml_score
  DL_VBF_resolved:
    - DL_VBF_resolved_ml_score
    
groups:
  '2022': !include samples_2022.yml
  '2022EE': !include samples_2022EE.yml
  '2023': !include samples_2023.yml
  '2023BPix': !include samples_2023BPix.yml