path: /afs/cern.ch/work/a/aguzel/private/bamboo_105/HHtoWWbb_Run3/output/v1.2.8-2022-mva_v1_2_3/

outputDir: /afs/cern.ch/work/a/aguzel/private/BambooDatacardProducer/wwbb-run3-datacards/output/v1.2.8-2022-mva_v1_2_3/

use_syst: True

# textfiles:

yamlName: plots.yml

era:
  - "2022"
  - "2022EE"

plotIt:
  legend:
    position:
      - 0.2
      - 0.7
      - 0.9
      - 0.9
    columns: 3

# combineConfigs:

normSyst:
  lumi:
    val: 1.013
    group: 
      - TT
      - DY
      - others

shapeSyst:
  # # Discard unwanted systematics
  # some_unwanted_syst: discard
  btagSF_shape_cferr1: btagSF_shape_cferr1
  btagSF_shape_lfstats1_2022: btagSF_shape_lfstats1_2022
  btagSF_shape_lfstats1_2022EE: btagSF_shape_lfstats1_2022EE
  pileup: pileup
  btagSF_shape_hfstats2_2022: btagSF_shape_hfstats2_2022
  btagSF_shape_hfstats2_2022EE: btagSF_shape_hfstats2_2022EE
  btagSF_shape_lfstats2_2022: btagSF_shape_lfstats2_2022
  btagSF_shape_lfstats2_2022EE: btagSF_shape_lfstats2_2022EE
  btagSF_shape_cferr2: btagSF_shape_cferr2
  jesTotal: jesTotal
  btagSF_shape_hfstats1_2022: btagSF_shape_hfstats1_2022
  btagSF_shape_hfstats1_2022EE: btagSF_shape_hfstats1_2022EE
  btagSF_shape_hf: btagSF_shape_hf
  btagSF_shape_lf: btagSF_shape_lf
  jer0: jer0
  jer1: jer1
  jer2: jer2
  jer3: jer3
  jer4: jer4
  jer5: jer5
  elIdSF: elIdSF
  elTrgSF: elTrgSF
  muonIdSF: muonIdSF
  muonIsoSF: muonIsoSF
  muonTrgSF: muonTrgSF
  pileup: pileup
  ZpT1: ZpT1
  ZpT2: ZpT2
  ZpT3: ZpT3
  ZpT4: ZpT4
  ZpT5: ZpT5
  ZpT6: ZpT6
  ZpT7: ZpT7
  ZpT8: ZpT8
  ZpT9: ZpT9
  ZpT10: ZpT10

quantiles: &quant [0., 0.4, 0.45, 0.5, 0.55, 0.625, 0.75, 0.875, 1.]
backgrounds: &backgrounds [TT, DY, others]

rebin:
  DL_score:
    method: quantile
    params: [*quant, *backgrounds]

#histCorrections:

histConverter:
  DL_boosted:
    - DL_boosted_ml_score
  DL_resolved1b:
    - DL_resolved1b_ml_score
  DL_resolved2b:
    - DL_resolved2b_ml_score
  DL_VBF_boosted:
    - DL_VBF_boosted_ml_score
  DL_VBF_resolved:
    - DL_VBF_resolved_ml_score

groups:
  "2022": !include samples_2022.yml
  "2022EE": !include samples_2022EE.yml