TT:
    type: mc
    fill-color: "#fff3b0"
    legend: "TT"
    files:
      - TTto2L2Nu_2022.root

DY:
  type: mc
  fill-color: "#9e2a2b"
  legend: "DY"
  files:
    - DYto2L-2Jets_MLL-50_2022.root
    - DYto2L-2Jets_MLL-10to50_2022.root

others:
  type: mc
  fill-color: "#2a2b60"
  legend: "others"
  files:
    - WtoLNu-2Jets_2022.root
    - WW_2022.root
    - WZ_2022.root
    - ZZ_2022.root
    - TbarWplusto2L2Nu_2022.root
    - TWminusto2L2Nu_2022.root

data_obs:
  type: data
  legend: "data"
  files:
    - Muon_Run2022C.root
    - Muon_Run2022D.root
    - DoubleMuon_Run2022C.root
    - SingleMuon_Run2022C.root
    - EGamma_Run2022C.root
    - EGamma_Run2022D.root
    - MuonEG_Run2022C.root
    - MuonEG_Run2022D.root

# ggHH_kl_0_kt_1_hbbhww:
#   type: signal
#   legend: "signal"
#   line-color: 3
#   files:
#     - ggH_bbww_2l2Nu_kl-0p00_kt-1p00_c2-0p00_2022.root


ggHH_kl_1_kt_1_hbbhww:
  type: signal
  legend: "signal"
  line-color: 3
  files:
    - ggH_bbww_2L2Nu_kl-1p00_kt-1p00_c2-0p00_2022.root


ggHH_kl_2p45_kt_1_hbbhww:
  type: signal
  legend: "signal"
  line-color: 4
  files:
    - ggH_bbww_2L2Nu_kl-2p45_kt-1p00_c2-0p00_2022.root


ggHH_kl_5_kt_1_hbbhww:
  type: signal
  legend: "signal"
  line-color: 5
  files:
    - ggH_bbww_2L2Nu_kl-5p00_kt-1p00_c2-0p00_2022.root


# qqHH_CV_1_C2V_1_kl_1_hbbhww:
#   type: signal
#   legend: "signal"
#   line-color: 6
#   files:
#     - VBF_bbww_2L2Nu_CV_1_C2V_1_C3_1_2022.root

# matching processes for vbf_formula:
#   qqHH_CV_1_C2V_1_kl_1   -> /VBFHHto2B2V_CV_1_C2V_1_C3_1_TuneCP5_13p6TeV_madgraph-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v3/NANOAODSIM
#   qqHH_CV_1_C2V_1_kl_0   -> MISSING
#   qqHH_CV_1_C2V_1_kl_2   -> MISSING
#   qqHH_CV_1_C2V_0_kl_1   -> /VBFHHto2B2V_CV_1_C2V_0_C3_1_TuneCP5_13p6TeV_madgraph-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v3/NANOAODSIM
#   qqHH_CV_1_C2V_2_kl_1   -> MISSING
#   qqHH_CV_1p5_C2V_1_kl_1 -> MISSING