TTbar:
    type: mc
    legend: "t#bar{t}"
    fill-color: "#bd1f01"
    files:
      - TTto2L2Nu_2023.root

DY:
  type: mc
  legend: "DY"
  fill-color: "#e76300"
  files:
    - DYto2L-2Jets_MLL-50_2023.root
    - DYto2L-2Jets_MLL-10to50_2023.root
    - DYto2L-2Jets_MLL-50_0J_2023.root
    - DYto2L-2Jets_MLL-50_1J_2023.root
    - DYto2L-2Jets_MLL-50_2J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-100to200_1J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-100to200_2J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-200to400_1J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-200to400_2J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-400to600_1J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-400to600_2J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-40to100_1J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-40to100_2J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-600_1J_2023.root
    - DYto2L-2Jets_MLL-50_PTLL-600_2J_2023.root

ST:
  type: mc
  legend: "ST"
  fill-color: "#ffa90e"
  files:
    - TbarWplusto2L2Nu_2023.root
    - TWminusto2L2Nu_2023.root
    - TBbar_2023.root
    - TBbarQ_2023.root

VV:
  type: mc
  legend: "VV"
  fill-color: "#92dadd"
  files:
    - WW_2023.root
    - WZ_2023.root
    - ZZ_2023.root

VJets:
  type: mc
  legend: "V+jets"
  fill-color: "#94a4a2"
  files:
    - WtoLNu-2Jets_0J_2023.root
    - WtoLNu-2Jets_1J_2023.root
    - WtoLNu-2Jets_2023.root
    - WtoLNu-2Jets_2J_2023.root
    - WtoLNu-2Jets_PTLNu-100to200_1J_2023.root
    - WtoLNu-2Jets_PTLNu-100to200_2J_2023.root
    - WtoLNu-2Jets_PTLNu-200to400_1J_2023.root
    - WtoLNu-2Jets_PTLNu-200to400_2J_2023.root
    - WtoLNu-2Jets_PTLNu-400to600_1J_2023.root
    - WtoLNu-2Jets_PTLNu-400to600_2J_2023.root
    - WtoLNu-2Jets_PTLNu-40to100_1J_2023.root
    - WtoLNu-2Jets_PTLNu-40to100_2J_2023.root
    - WtoLNu-2Jets_PTLNu-600_1J_2023.root
    - WtoLNu-2Jets_PTLNu-600_2J_2023.root
    - Zto2Nu-2Jets_PTNuNu-100to200_1J_2023.root
    - Zto2Nu-2Jets_PTNuNu-100to200_2J_2023.root
    - Zto2Nu-2Jets_PTNuNu-200to400_1J_2023.root
    - Zto2Nu-2Jets_PTNuNu-200to400_2J_2023.root
    - Zto2Nu-2Jets_PTNuNu-400to600_1J_2023.root
    - Zto2Nu-2Jets_PTNuNu-400to600_2J_2023.root
    - Zto2Nu-2Jets_PTNuNu-40to100_1J_2023.root
    - Zto2Nu-2Jets_PTNuNu-40to100_2J_2023.root
    - Zto2Nu-2Jets_PTNuNu-600_1J_2023.root
    - Zto2Nu-2Jets_PTNuNu-600_2J_2023.root

other:
  type: mc
  legend: "other"
  fill-color: "#800080"
  files:
    - TTLL_2023.root
    - TTZ_2023.root
    - TTTT_2023.root
    - GluGluHto2Wto2L2Nu_2023.root
    - VBFHto2Wto2L2Nu_2023.root
    - WplusH_2023.root
    - ttH_2023.root
    - ZH_2023.root
    - THQ_2023.root
    - THW_2023.root

data_obs:
  type: data
  legend: "data"
  files:
    - Muon_Run2023C.root
    - EGamma_Run2023C.root
    - MuonEG_Run2023C.root

ggHH_kl_0_kt_1_hbbhww:
  type: signal
  legend: 'HH_{ggf}^{\kappa_\lambda=0}\rightarrow bbWW'
  line-color: 3
  files:
    - ggH_bbww_2L2Nu_kl-0p00_kt-1p00_c2-0p00_2023.root


ggHH_kl_1_kt_1_hbbhww:
  type: signal
  legend: 'HH_{ggF}^{SM}\rightarrow bbWW'
  line-color: 3
  files:
    - ggH_bbww_2L2Nu_kl-1p00_kt-1p00_c2-0p00_2023.root


ggHH_kl_2p45_kt_1_hbbhww:
  type: signal
  legend: 'HH_{ggf}^{\kappa_\lambda=2.45}\rightarrow bbWW'
  line-color: 4
  files:
    - ggH_bbww_2L2Nu_kl-2p45_kt-1p00_c2-0p00_2023.root


ggHH_kl_5_kt_1_hbbhww:
  type: signal
  legend: 'HH_{ggf}^{\kappa_\lambda=5}\rightarrow bbWW'
  line-color: 5
  files:
    - ggH_bbww_2L2Nu_kl-5p00_kt-1p00_c2-0p00_2023.root


qqHH_CV_1_C2V_1_kl_1_hbbhww:
  type: signal
  legend: 'HH_{VBF}^{SM}\rightarrow bbWW'
  line-color: 6
  files:
    - VBF_bbww_2L2Nu_CV_1_C2V_1_C3_1_2023.root

qqHH_CV_1p74_C2V_1p37_C3_14p4_hbbhww:
  type: signal
  legend: 'HH\rightarrow bbWW vbf (MCHM5)'
  line-color: 6
  files:
    - VBF_bbww_2L2Nu_CV_1p74_C2V_1p37_C3_14p4_2023.root

qqHH_CV_m0p962_C2V_m0p959_C3_m1p43_hbbhww:
  type: signal
  legend: 'HH\rightarrow bbWW vbf (MCHM4)'
  line-color: 7
  files:
    - VBF_bbww_2L2Nu_CV_m0p962_C2V_m0p959_C3_m1p43_2023.root

qqHH_CV_m0p758_C2V_1p44_C3_m19p3_hbbhww:
  type: signal
  legend: 'HH\rightarrow bbWW vbf (MCHM4 with f=500 GeV)'
  line-color: 8
  files:
    - VBF_bbww_2L2Nu_CV_m0p758_C2V_1p44_C3_m19p3_2023.root

qqHH_CV_m1p60_C2V_m2p72_C3_m1p36_hbbhww:
  type: signal
  legend: 'HH\rightarrow bbWW vbf (MCHM4 with f=800 GeV)'
  line-color: 9
  files:
    - VBF_bbww_2L2Nu_CV_m1p60_C2V_m2p72_C3_m1p36_2023.root

qqHH_CV_m0p012_C2V_m0p030_C3_m10p2_hbbhww:
  type: signal
  legend: 'HH\rightarrow bbWW vbf (MCHM4 with f=100 TeV)'
  line-color: 10
  files:
    - VBF_bbww_2L2Nu_CV_m0p012_C2V_m0p030_C3_m10p2_2023.root

qqHH_CV_m1p21_C2V_m1p94_C3_m0p94_hbbhww:
  type: signal
  legend: 'HH\rightarrow bbWW vbf (MCHM4 with f=200 GeV)'
  line-color: 11
  files:
    - VBF_bbww_2L2Nu_CV_m1p21_C2V_m1p94_C3_m0p94_2023.root

qqHH_CV_m1p83_C2V_m3p57_C3_m3p39_hbbhww:
  type: signal
  legend: 'HH\rightarrow bbWW vbf (MCHM4 with f=150 GeV)'
  line-color: 12
  files:
    - VBF_bbww_2L2Nu_CV_m1p83_C2V_m3p57_C3_m3p39_2023.root

qqHH_CV_m2p12_C2V_m3p87_C3_m5p96_hbbhww:
  type: signal
  legend: 'HH\rightarrow bbWW vbf (MCHM4 with f=120 GeV)'
  line-color: 13
  files:
    - VBF_bbww_2L2Nu_CV_m2p12_C2V_m3p87_C3_m5p96_2023.root

# matching processes for vbf_formula:
#   qqHH_CV_1_C2V_1_kl_1   -> /VBFHHto2B2V_CV_1_C2V_1_C3_1_TuneCP5_13p6TeV_madgraph-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2023_realistic_postEE_v6-v3/NANOAODSIM
#   qqHH_CV_1_C2V_1_kl_0   -> MISSING
#   qqHH_CV_1_C2V_1_kl_2   -> MISSING
#   qqHH_CV_1_C2V_0_kl_1   -> /VBFHHto2B2V_CV_1_C2V_0_C3_1_TuneCP5_13p6TeV_madgraph-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2023_realistic_v5-v3/NANOAODSIM
#   qqHH_CV_1_C2V_2_kl_1   -> MISSING
#   qqHH_CV_1p5_C2V_1_kl_1 -> MISSING