TTbar:
    type: mc
    legend: "t#bar{t}"
    fill-color: "#bd1f01"
    files:
      - TTto2L2Nu_2023BPix.root

DY:
  type: mc
  legend: "DY"
  fill-color: "#e76300"
  files:
    - DYto2L-2Jets_MLL-50_2023BPix.root
    - DYto2L-2Jets_MLL-10to50_2023BPix.root
    - DYto2L-2Jets_MLL-50_0J_2023BPix.root
    - DYto2L-2Jets_MLL-50_1J_2023BPix.root
    - DYto2L-2Jets_MLL-50_2J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-100to200_1J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-100to200_2J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-200to400_1J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-200to400_2J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-400to600_1J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-400to600_2J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-40to100_1J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-40to100_2J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-600_1J_2023BPix.root
    - DYto2L-2Jets_MLL-50_PTLL-600_2J_2023BPix.root

ST:
  type: mc
  legend: "ST"
  fill-color: "#ffa90e"
  files:
    - TbarWplusto2L2Nu_2023BPix.root
    - TWminusto2L2Nu_2023BPix.root
    - TBbar_2023BPix.root
    - TBbarQ_2023BPix.root

VV:
  type: mc
  legend: "VV"
  fill-color: "#92dadd"
  files:
    - WW_2023BPix.root
    - WZ_2023BPix.root
    - ZZ_2023BPix.root

VJets:
  type: mc
  legend: "V+jets"
  fill-color: "#94a4a2"
  files:
    - WtoLNu-2Jets_0J_2023BPix.root
    - WtoLNu-2Jets_1J_2023BPix.root
    - WtoLNu-2Jets_2023BPix.root
    - WtoLNu-2Jets_2J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-100to200_1J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-100to200_2J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-200to400_1J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-200to400_2J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-400to600_1J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-400to600_2J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-40to100_1J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-40to100_2J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-600_1J_2023BPix.root
    - WtoLNu-2Jets_PTLNu-600_2J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-100to200_1J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-100to200_2J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-200to400_1J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-200to400_2J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-400to600_1J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-400to600_2J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-40to100_1J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-40to100_2J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-600_1J_2023BPix.root
    - Zto2Nu-2Jets_PTNuNu-600_2J_2023BPix.root

other:
  type: mc
  legend: "other"
  fill-color: "#800080"
  files:
    - TTLL_2023BPix.root
    - TTZ_2023BPix.root
    - TTTT_2023BPix.root
    - GluGluHto2Wto2L2Nu_2023BPix.root
    - VBFHto2Wto2L2Nu_2023BPix.root
    - WplusH_2023BPix.root
    - ttH_2023BPix.root
    - ZH_2023BPix.root
    - THQ_2023BPix.root
    - THW_2023BPix.root

data_obs:
  type: data
  legend: "data"
  files:
    - Muon_Run2023D.root
    - EGamma_Run2023D.root
    - MuonEG_Run2023D.root

# ggHH_kl_0_kt_1_hbbhww:
#   type: signal
#   legend: 'HH_{ggf}^{\kappa_\lambda=0}\rightarrow bbWW'
#   line-color: 3
#   files:
#     - ggH_bbww_2l2Nu_kl-0p00_kt-1p00_c2-0p00_2023BPix.root


ggHH_kl_1_kt_1_hbbhww:
  type: signal
  legend: 'HH_{ggF}^{SM}\rightarrow bbWW'
  line-color: 3
  files:
    - ggH_bbww_2L2Nu_kl-1p00_kt-1p00_c2-0p00_2023BPix.root


# ggHH_kl_2p45_kt_1_hbbhww:
#   type: signal
#   legend: 'HH_{ggf}^{\kappa_\lambda=2.45}\rightarrow bbWW'
#   line-color: 4
#   files:
#     - ggH_bbww_2L2Nu_kl-2p45_kt-1p00_c2-0p00_2023BPix.root


# ggHH_kl_5_kt_1_hbbhww:
#   type: signal
#   legend: 'HH_{ggf}^{\kappa_\lambda=5}\rightarrow bbWW'
#   line-color: 5
#   files:
#     - ggH_bbww_2L2Nu_kl-5p00_kt-1p00_c2-0p00_2023BPix.root


qqHH_CV_1_C2V_1_kl_1_hbbhww:
  type: signal
  legend: 'HH_{VBF}^{SM}\rightarrow bbWW'
  line-color: 6
  files:
    - VBF_bbww_2L2Nu_CV_1_C2V_1_C3_1_2023BPix.root

# matching processes for vbf_formula:
#   qqHH_CV_1_C2V_1_kl_1   -> /VBFHHto2B2V_CV_1_C2V_1_C3_1_TuneCP5_13p6TeV_madgraph-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2023BPix_realistic_postEE_v6-v3/NANOAODSIM
#   qqHH_CV_1_C2V_1_kl_0   -> MISSING
#   qqHH_CV_1_C2V_1_kl_2   -> MISSING
#   qqHH_CV_1_C2V_0_kl_1   -> /VBFHHto2B2V_CV_1_C2V_0_C3_1_TuneCP5_13p6TeV_madgraph-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2023BPix_realistic_v5-v3/NANOAODSIM
#   qqHH_CV_1_C2V_2_kl_1   -> MISSING
#   qqHH_CV_1p5_C2V_1_kl_1 -> MISSING